# Generated by Django 5.1.6 on 2025-04-07 04:26

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='hero',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subheader',
            field=models.CharField(default='Subheader', max_length=255),
        ),
    ]
