# Generated by Django 5.1.6 on 2025-04-07 04:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_body_destination_hero_destination_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description_one',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_three',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='description_two',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='destination',
            name='header',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='destination',
            name='subheader',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='subheader'),
        ),
        migrations.AddField(
            model_name='destination',
            name='subheader_one',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='subheader_one'),
        ),
        migrations.AddField(
            model_name='destination',
            name='subheader_three',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='subheader_three'),
        ),
        migrations.AddField(
            model_name='destination',
            name='subheader_two',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='subheader_two'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description'),
        ),
    ]
