# Generated by Django 5.1.6 on 2025-04-08 01:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_description_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description_one',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description_one'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_three',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description_three'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description_two',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description_two'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='header',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='subheader',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='subheader_one',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='subheader_three',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='subheader_two',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
    ]
