# Generated by Django 5.1.6 on 2025-04-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_description_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image',
            new_name='image_banner',
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
