# Generated by Django 5.1.6 on 2025-04-28 20:05

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_rename_image_destination_image_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional: Add a custom meta description for SEO.', max_length=1160),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=655),
            preserve_default=False,
        ),
    ]
