# Generated by Django 5.1.6 on 2025-04-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_tag_remove_post_content_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/sections/'),
        ),
    ]
