# Generated by Django 5.1.6 on 2025-04-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_slug_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional: Add a custom meta description for SEO.', max_length=160),
        ),
    ]
