# Generated by Django 5.1.6 on 2025-04-15 22:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='body'),
        ),
    ]
