# Generated by Django 5.1.6 on 2025-04-27 23:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional: Add a custom meta description for SEO.', max_length=1160),
        ),
    ]
