# Generated by Django 5.1.6 on 2025-04-27 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_question_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='meta_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=655),
            preserve_default=False,
        ),
    ]
