# Generated by Django 5.1.6 on 2025-04-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('hotels', 'Hotels'), ('tours', 'Tours'), ('airlines', 'Airlines'), ('boards', 'Boards')], default='hotels', max_length=50),
        ),
    ]
