# Generated by Django 5.1.6 on 2025-04-14 00:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='process_images/')),
                ('image2', models.ImageField(upload_to='process_images/')),
                ('image3', models.ImageField(upload_to='process_images/')),
                ('image4', models.ImageField(upload_to='process_images/')),
                ('header', models.CharField(max_length=255)),
                ('subheader1', models.CharField(max_length=255)),
                ('subheader2', models.CharField(max_length=255)),
                ('subheader3', models.CharField(max_length=255)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='body')),
                ('description1', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description1')),
                ('description2', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description2')),
                ('description3', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
