# Generated by Django 5.1.6 on 2025-05-04 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='leaving',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
