# Generated by Django 5.1.6 on 2025-04-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('subheader_1', models.CharField(blank=True, max_length=255, null=True)),
                ('body_1', models.TextField(blank=True, null=True)),
                ('subheader_2', models.CharField(blank=True, max_length=255, null=True)),
                ('body_2', models.TextField(blank=True, null=True)),
                ('subheader_3', models.CharField(blank=True, max_length=255, null=True)),
                ('body_3', models.TextField(blank=True, null=True)),
                ('subheader_4', models.CharField(blank=True, max_length=255, null=True)),
                ('body_4', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='service/')),
            ],
        ),
    ]
