# Generated by Django 5.1.6 on 2025-04-14 00:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body_1',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='body1'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body_2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='body2'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='body_3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='body3'),
        ),
    ]
