# Generated by Django 5.1.6 on 2025-04-27 23:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicepage_body_alter_servicepage_body_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional: Add a custom meta description for SEO.', max_length=1160),
        ),
    ]
