# Generated by Django 5.1.6 on 2025-04-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('header', models.CharField(max_length=255)),
                ('subheader', models.TextField()),
                ('smallsubheader', models.TextField()),
                ('body', models.TextField()),
                ('country', models.CharField(max_length=300)),
                ('hero', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='destinations.destination')),
            ],
        ),
    ]
