# Generated by Django 5.1.6 on 2025-04-08 01:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='city',
            name='smallsubheader',
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_one',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description_one'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_three',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description_three'),
        ),
        migrations.AddField(
            model_name='city',
            name='description_two',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='description_two'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='city',
            name='subheader_one',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='subheader_three',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='subheader_two',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='city',
            name='header',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='hero',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='subheader',
            field=models.CharField(default='Unnamed Destination', max_length=255),
        ),
    ]
