# Generated by Django 5.1.6 on 2025-04-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('subheader_1', models.CharField(blank=True, max_length=255, null=True)),
                ('subheader_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about.aboutpage')),
            ],
        ),
    ]
