# Generated by Django 5.1.6 on 2025-04-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_aboutpage_subheader_2_alter_aboutpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional: Add a custom meta description for SEO.', max_length=160),
        ),
    ]
