# Generated by Django 5.1.6 on 2025-04-28 19:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpage_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional: Add a custom meta description for SEO.', max_length=1160),
        ),
    ]
