# Generated by Django 5.1.6 on 2025-02-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=6)),
                ('mobile_title', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='carousel_mobile_images/')),
                ('mobile_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_button_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
