# Generated by Django 5.1.6 on 2025-02-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_itiniraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItinerarySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_1_title', models.CharField(max_length=255)),
                ('itinerary_1_date', models.DateField()),
                ('itinerary_1_image', models.ImageField(upload_to='itineraries/')),
                ('itinerary_1_link', models.URLField()),
                ('itinerary_2_title', models.CharField(max_length=255)),
                ('itinerary_2_date', models.DateField()),
                ('itinerary_2_image', models.ImageField(upload_to='itineraries/')),
                ('itinerary_2_link', models.URLField()),
                ('itinerary_3_title', models.CharField(max_length=255)),
                ('itinerary_3_date', models.DateField()),
                ('itinerary_3_image', models.ImageField(upload_to='itineraries/')),
                ('itinerary_3_link', models.URLField()),
                ('itinerary_4_title', models.CharField(max_length=255)),
                ('itinerary_4_date', models.DateField()),
                ('itinerary_4_image', models.ImageField(upload_to='itineraries/')),
                ('itinerary_4_link', models.URLField()),
                ('itinerary_5_title', models.CharField(max_length=255)),
                ('itinerary_5_date', models.DateField()),
                ('itinerary_5_image', models.ImageField(upload_to='itineraries/')),
                ('itinerary_5_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='ItiniraryItem',
        ),
    ]
