# Generated by Django 5.1.6 on 2025-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_itinerarysection_delete_itiniraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('header', models.CharField(max_length=200)),
                ('subheader', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField()),
                ('grade', models.CharField(help_text='Example: starstarstarstarstar', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='itinerarysection',
            name='itinerary_1_date',
        ),
        migrations.RemoveField(
            model_name='itinerarysection',
            name='itinerary_2_date',
        ),
        migrations.RemoveField(
            model_name='itinerarysection',
            name='itinerary_3_date',
        ),
        migrations.RemoveField(
            model_name='itinerarysection',
            name='itinerary_4_date',
        ),
        migrations.RemoveField(
            model_name='itinerarysection',
            name='itinerary_5_date',
        ),
    ]
