# Generated by Django 5.1.6 on 2025-04-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_gallerygrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_1',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_10',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_11',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_12',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_2',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_3',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_4',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_5',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_6',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_7',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_8',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_9',
            field=models.CharField(help_text='e.g. starstarstarstarstar', max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
