# Generated by Django 5.1.6 on 2025-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_banner_alter_gallerygrid_price_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='trends/')),
                ('link', models.URLField()),
            ],
        ),
    ]
