# Generated by Django 5.1.6 on 2025-04-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_trend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_1',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_10',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_11',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_12',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_2',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_3',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_4',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_5',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_6',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_7',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_8',
        ),
        migrations.RemoveField(
            model_name='gallerygrid',
            name='img_link_9',
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_11',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_12',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_11',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_12',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='location_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_10',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_11',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_12',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_7',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='page_link_9',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_1',
            field=models.CharField(help_text='e.g. ⭐️⭐️⭐️⭐️⭐️', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='stars_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_11',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_12',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerygrid',
            name='title_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
