# Generated by Django 5.1.6 on 2025-04-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_gallerygrid_img_link_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='banner_image',
        ),
    ]
