# Generated by Django 5.1.6 on 2025-04-29 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_rename_image_banner_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysection',
            name='itinerary_1_destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarysection',
            name='itinerary_2_destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarysection',
            name='itinerary_3_destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarysection',
            name='itinerary_4_destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarysection',
            name='itinerary_5_destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
